name: Java CI with Gradle

on:
  push:
    branches: [ "1.20/dev" ]
  pull_request:
    branches: [ "1.20/dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Get latest commit hash
        id: get_hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get MC version
        uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b
        id: read_properties
        with:
          path: gradle.properties
          properties: minecraft_version enabled_platforms mod_version archives_base_name

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@9aa31f26bc8e536d1faf4b332bb8365350743a18

      - name: Build jar
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: build
          gradle-home-cache-includes: |
            caches
            loom-cache
     
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.read_properties.outputs.archives_base_name }}-${{ steps.read_properties.outputs.minecraft_version }}-${{ steps.read_properties.outputs.mod_version }}-nightly-${{ steps.get_hash.outputs.sha_short }}
          path: ${{ steps.find_jars.outputs.jars }}
